### PR TITLE
fix: proper processing of routing headers

### LINKED ISSUE #569: cloud run API: linting error in the generated code
image

```
src/v2/services_client.ts#L1035
Optional chain expressions can return undefined by design - using a non-null assertion is unsafe and wrong
```

### LINKED ISSUE #1154: cloud run API: linting error in the generated code
image

```
src/v2/services_client.ts#L1035
Optional chain expressions can return undefined by design - using a non-null assertion is unsafe and wrong
```

### PR DESCRIPTION
**Pull request by alexander-fenster**
Fixes googleapis/google-cloud-node-core#569.

A huge refactor of the routing header processing logic to fix the Cloud Run use case. Tested locally, the generated Cloud Run client works (successfully providing the `location` routing header).

### CODE REVIEW

File: typescript/src/util.ts [hunk 1]
```diff
@@ -221,144 +221,35 @@ export function getResourceNameByPattern(pattern: string): string {
...
-): boolean {
-  let countOfNamedSegments = 0;
-  // Checks that resources are named
-  const regexNamed = new RegExp(/^.+=.+/);
-  const regexWildcard = new RegExp(/^{[a-zA-Z\d-]+}/);
-  pattern.forEach(element => {
-    if (regexNamed.test(element) || regexWildcard.test(element)) {
-      countOfNamedSegments++;
-    }
+export function processPathTemplate(
```
Comment (sofisl) [inline typescript/src/util.ts:224]: Would you mind adding a comment for this function? I'm not quite sure what it does, or how it replaces all the deleted functions in TS.

File: typescript/src/schema/proto.ts [hunk 2]
```diff
@@ -703,19 +701,20 @@ export function getSingleRoutingHeaderParam(
...
-      messageRegex: '[^/]+',
-      namedSegment: '[^/]+',
+      messageRegex: `(?<${rule.field}>.*)`,
     };
   }
   // If the annotation is malformed, then return empty interface
-  else if (getNamedSegment(rule.pathTemplate).length < 1) {
-    return dynamicRoutingRule;
-  } else {
+  else {
```
Comment (sofisl) [inline typescript/src/schema/proto.ts:708]: I assume that if the annotation is malformed, those values don't get appended to the header. What happens to the request in that case?

File: baselines/routingtest/src/v1/test_service_client.ts.baseline [hunk 3]
```diff
@@ -422,17 +430,33 @@ export class TestServiceClient {
...
     options.otherArgs = options.otherArgs || {};
     options.otherArgs.headers = options.otherArgs.headers || {};let routingParameter = {};
-      if ((typeof request.name !== "undefined") && RegExp('[^/]+').test(request.name!)){
-        Object.assign(routingParameter, { name: request.name!.match(RegExp('[^/]+'))![0]})}
+    {
+      const fieldValue = request.name;
+      if (fieldValue !== undefined && fieldValue !== null) {
+        const match = fieldValue.toString().match(RegExp('(?<name>.*)'));
+        if (match) {
+          const parameterValue = match.groups?.['name'] ?? fieldValue;
```
Comment (sofisl) [inline baselines/routingtest/src/v1/test_service_client.ts.baseline:438]: are these changes safe to make to other APIs? (i.e., can we/should we send those values in the header for APIs other than cloud run?)

File: typescript/src/schema/proto.ts (hunk 2 above)
Comment (alexander-fenster) [reply typescript/src/schema/proto.ts:708]: At this moment, only two APIs (BigTable and CloudRun) use this functionality, and I checked that everything works :)

File: typescript/src/util.ts (hunk 1 above)
Comment (alexander-fenster) [reply typescript/src/util.ts:224]: Sure!

File: typescript/src/schema/proto.ts (hunk 2 above)
Comment (alexander-fenster) [reply typescript/src/schema/proto.ts:708]: Most likely it will fail on the backend. The client library is not supposed to validate the request, it's OK to let it through and let the backend respond.

**Review by sofisl — APPROVED** [review]
